# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(462, 600)
        font = QtGui.QFont()
        font.setPointSize(12)
        mainWindow.setFont(font)
        mainWindow.setStyleSheet("QWidget#centralwidget {\n"
"    background-image: url(resized_background.jpeg);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    background-attachment: fixed;\n"
"    background-size: cover;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(0, 10, 192, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 300, 255, 166))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.runningIntervalCombo = QtWidgets.QComboBox(self.layoutWidget)
        self.runningIntervalCombo.setObjectName("runningIntervalCombo")
        self.runningIntervalCombo.addItem("")
        self.runningIntervalCombo.addItem("")
        self.runningIntervalCombo.addItem("")
        self.runningIntervalCombo.addItem("")
        self.runningIntervalCombo.addItem("")
        self.runningIntervalCombo.addItem("")
        self.runningIntervalCombo.addItem("")
        self.runningIntervalCombo.addItem("")
        self.runningIntervalCombo.addItem("")
        self.runningIntervalCombo.addItem("")
        self.verticalLayout.addWidget(self.runningIntervalCombo)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.headlessCombo = QtWidgets.QComboBox(self.layoutWidget)
        self.headlessCombo.setObjectName("headlessCombo")
        self.headlessCombo.addItem("")
        self.headlessCombo.addItem("")
        self.verticalLayout_2.addWidget(self.headlessCombo)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.startButton = QtWidgets.QPushButton(self.layoutWidget)
        self.startButton.setObjectName("startButton")
        self.verticalLayout_9.addWidget(self.startButton)
        self.verticalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.outputEditText = QtWidgets.QTextEdit(self.centralwidget)
        self.outputEditText.setGeometry(QtCore.QRect(0, 60, 461, 201))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.outputEditText.setFont(font)
        self.outputEditText.setStyleSheet("QTextEdit {\n"
"    background-color: black;\n"
"    color: blue;\n"
"}\n"
"")
        self.outputEditText.setObjectName("outputEditText")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 462, 37))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "微所自动联网系统"))
        self.label_8.setText(_translate("mainWindow", "处理情况"))
        self.label.setText(_translate("mainWindow", "运行频率(多少分钟一次)"))
        self.runningIntervalCombo.setItemText(0, _translate("mainWindow", "60"))
        self.runningIntervalCombo.setItemText(1, _translate("mainWindow", "1"))
        self.runningIntervalCombo.setItemText(2, _translate("mainWindow", "5"))
        self.runningIntervalCombo.setItemText(3, _translate("mainWindow", "10"))
        self.runningIntervalCombo.setItemText(4, _translate("mainWindow", "15"))
        self.runningIntervalCombo.setItemText(5, _translate("mainWindow", "30"))
        self.runningIntervalCombo.setItemText(6, _translate("mainWindow", "120"))
        self.runningIntervalCombo.setItemText(7, _translate("mainWindow", "240"))
        self.runningIntervalCombo.setItemText(8, _translate("mainWindow", "480"))
        self.runningIntervalCombo.setItemText(9, _translate("mainWindow", "New Item"))
        self.label_2.setText(_translate("mainWindow", "是否启动无头模式（启动后不会打开浏览器）"))
        self.headlessCombo.setItemText(0, _translate("mainWindow", "是"))
        self.headlessCombo.setItemText(1, _translate("mainWindow", "否"))
        self.startButton.setText(_translate("mainWindow", "启动"))
        self.outputEditText.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\';\"><br /></p></body></html>"))
        self.menu.setTitle(_translate("mainWindow", "文件"))
